// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commondefine.proto

#ifndef PROTOBUF_commondefine_2eproto__INCLUDED
#define PROTOBUF_commondefine_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Micro {
namespace Future {
namespace Message {
namespace Business {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_commondefine_2eproto();
void protobuf_AssignDesc_commondefine_2eproto();
void protobuf_ShutdownFile_commondefine_2eproto();

class DataHeader;

// ===================================================================

class DataHeader : public ::google::protobuf::Message {
 public:
  DataHeader();
  virtual ~DataHeader();

  DataHeader(const DataHeader& from);

  inline DataHeader& operator=(const DataHeader& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DataHeader& default_instance();

  void Swap(DataHeader* other);

  // implements Message ----------------------------------------------

  inline DataHeader* New() const { return New(NULL); }

  DataHeader* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataHeader& from);
  void MergeFrom(const DataHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DataHeader* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 serialId = 1;
  void clear_serialid();
  static const int kSerialIdFieldNumber = 1;
  ::google::protobuf::uint32 serialid() const;
  void set_serialid(::google::protobuf::uint32 value);

  // optional bool hasMore = 2;
  void clear_hasmore();
  static const int kHasMoreFieldNumber = 2;
  bool hasmore() const;
  void set_hasmore(bool value);

  // @@protoc_insertion_point(class_scope:Micro.Future.Message.Business.DataHeader)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 serialid_;
  bool hasmore_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_commondefine_2eproto();
  friend void protobuf_AssignDesc_commondefine_2eproto();
  friend void protobuf_ShutdownFile_commondefine_2eproto();

  void InitAsDefaultInstance();
  static DataHeader* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DataHeader

// optional uint32 serialId = 1;
inline void DataHeader::clear_serialid() {
  serialid_ = 0u;
}
inline ::google::protobuf::uint32 DataHeader::serialid() const {
  // @@protoc_insertion_point(field_get:Micro.Future.Message.Business.DataHeader.serialId)
  return serialid_;
}
inline void DataHeader::set_serialid(::google::protobuf::uint32 value) {
  
  serialid_ = value;
  // @@protoc_insertion_point(field_set:Micro.Future.Message.Business.DataHeader.serialId)
}

// optional bool hasMore = 2;
inline void DataHeader::clear_hasmore() {
  hasmore_ = false;
}
inline bool DataHeader::hasmore() const {
  // @@protoc_insertion_point(field_get:Micro.Future.Message.Business.DataHeader.hasMore)
  return hasmore_;
}
inline void DataHeader::set_hasmore(bool value) {
  
  hasmore_ = value;
  // @@protoc_insertion_point(field_set:Micro.Future.Message.Business.DataHeader.hasMore)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Business
}  // namespace Message
}  // namespace Future
}  // namespace Micro

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_commondefine_2eproto__INCLUDED
